version: 2

sources:
  - name: datafeed_schema
    database: mydb
    schema: RAW_SCHEMA
    tables:
      - name: RAW_CUSTOMER
      - name: RAW_ORDERS
        columns:
              - name: id
                tests:
                  - unique
                  - not_null
              - name: status
                tests:
                  - accepted_values:
                        values: ['placed', 'shipped', 'completed', 'returned', 'return_pending']
      - name: SNAP_CUSTOMERS
